-- Step 0: 重命名旧表
ALTER TABLE user RENAME TO user_old;

-- Step 1: 创建新表
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nick` varchar(32) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `sess` varchar(32) DEFAULT NULL,
  `activation` varchar(32) DEFAULT NULL,
  `ban` int(11) NOT NULL DEFAULT '0',
  `ban_pr` varchar(64) DEFAULT NULL,
  `ip` VARCHAR(39) DEFAULT NULL,
  `ua` varchar(128) DEFAULT NULL,
  `date_reg` int(11) NOT NULL DEFAULT '0',
  `time` int(11) DEFAULT NULL,
  `date_aut` int(11) NOT NULL DEFAULT '0',
  `date_last` int(11) NOT NULL DEFAULT '0',
  `balls` int(11) NOT NULL DEFAULT '0',
  `rating` int(11) NOT NULL DEFAULT '0',
  `level` enum('0','1','2','3','4') NOT NULL DEFAULT '0',
  `group_access` int(10) unsigned NOT NULL DEFAULT '0',
  `pol` enum('0','1') NOT NULL DEFAULT '1',
  `url` varchar(64) NOT NULL DEFAULT '/',
  `show_url` enum('0','1') NOT NULL DEFAULT '1',
  `ank_g_r` int(4) DEFAULT NULL,
  `ank_m_r` int(2) DEFAULT NULL,
  `ank_d_r` int(2) DEFAULT NULL,
  `ank_city` varchar(32) DEFAULT NULL,
  `ank_o_sebe` varchar(512) DEFAULT NULL,
  `ank_icq` varchar(10) DEFAULT NULL,
  `ank_skype` varchar(16) DEFAULT NULL,
  `email` varchar(32) DEFAULT NULL,
  `ank_n_tel` varchar(11) DEFAULT NULL,
  `ank_name` varchar(32) DEFAULT NULL,
  `set_time_chat` int(11) DEFAULT '0',
  `set_p_str` int(11) DEFAULT '7',
  `set_show_icon` set('0','1','2') DEFAULT '1',
  `set_translit` enum('0','1') NOT NULL DEFAULT '1',
  `set_files` enum('0','1') NOT NULL DEFAULT '0',
  `set_timesdvig` int(11) NOT NULL DEFAULT '0',
  `set_news_to_mail` enum('0','1') NOT NULL DEFAULT '0',
  `set_show_mail` enum('0','1') NOT NULL DEFAULT '0',
  `set_them` varchar(32) DEFAULT 'default',
  `set_them2` varchar(32) DEFAULT 'web',
  `meteo_country` int(11) NOT NULL DEFAULT '0',
  `autorization` enum('0','1') NOT NULL DEFAULT '0',
  `add_konts` enum('0','1','2') NOT NULL DEFAULT '1',
  `wall` int(1) DEFAULT '1',
  `browser` varchar(3) DEFAULT 'wap',
  `rating_tmp` int(11) DEFAULT '0',
  `sort` int(1) DEFAULT '0',
  `news_read` int(1) DEFAULT '0',
  `ban_where` varchar(10) DEFAULT NULL,
  `abuld` int(1) DEFAULT '0',
  `type_reg` varchar(100) DEFAULT NULL,
  `identity` varchar(100) DEFAULT NULL,
  `money` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `nick` (`nick`),
  KEY `url` (`url`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Step 2: 插入数据到新表
INSERT INTO `user` (
  `id`,
  `nick`, 
  `pass`, 
  `sess`, 
  `activation`, 
  `ban`, 
  `ban_pr`, 
  `ip`, 
  `ua`, 
  `date_reg`, 
  `time`, 
  `date_aut`, 
  `date_last`, 
  `balls`, 
  `rating`, 
  `level`, 
  `group_access`, 
  `pol`, 
  `url`, 
  `show_url`, 
  `ank_g_r`, 
  `ank_m_r`, 
  `ank_d_r`, 
  `ank_city`, 
  `ank_o_sebe`, 
  `ank_icq`, 
  `ank_skype`, 
  `email`, 
  `ank_n_tel`, 
  `ank_name`, 
  `set_time_chat`, 
  `set_p_str`, 
  `set_show_icon`, 
  `set_translit`, 
  `set_files`, 
  `set_timesdvig`, 
  `set_news_to_mail`, 
  `set_show_mail`, 
  `set_them`, 
  `set_them2`, 
  `meteo_country`, 
  `autorization`, 
  `add_konts`, 
  `wall`, 
  `browser`, 
  `rating_tmp`, 
  `sort`, 
  `news_read`, 
  `ban_where`, 
  `abuld`, 
  `type_reg`, 
  `identity`, 
  `money`
)
SELECT 
  `id`,
  `nick`, 
  `pass`, 
  `sess`, 
  `activation`, 
  `ban`, 
  `ban_pr`, 
  -- 将旧表的 IP 字段转换为新表的格式（这里假设它是 IPv4 格式，直接转换为字符串）
  INET_NTOA(`ip`) AS `ip`, 
  `ua`, 
  `date_reg`, 
  `time`, 
  `date_aut`, 
  `date_last`, 
  `balls`, 
  `rating`, 
  `level`, 
  `group_access`, 
  `pol`, 
  `url`, 
  `show_url`, 
  `ank_g_r`, 
  `ank_m_r`, 
  `ank_d_r`, 
  `ank_city`, 
  `ank_o_sebe`, 
  `ank_icq`, 
  `ank_skype`, 
  `ank_mail` AS `email`, 
  `ank_n_tel`, 
  `ank_name`, 
  `set_time_chat`, 
  `set_p_str`, 
  `set_show_icon`, 
  `set_translit`, 
  `set_files`, 
  `set_timesdvig`, 
  `set_news_to_mail`, 
  `set_show_mail`, 
  `set_them`, 
  `set_them2`, 
  `meteo_country`, 
  `autorization`, 
  `add_konts`, 
  `wall`, 
  `browser`, 
  `rating_tmp`, 
  `sort`, 
  `news_read`, 
  `ban_where`, 
  `abuld`, 
  `type_reg`, 
  `identity`, 
  `money`
FROM `user_old`; -- 旧表的表名（假设旧表名为 `user_old`）

-- Step 3: 删除旧表
DROP TABLE `user_old`;

UPDATE `user`
SET `group_access` = 1
WHERE `group_access` = 0;
